FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build
RUN ls -al /app

FROM nginx:stable-alpine
RUN rm -r /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html
COPY production-nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]