services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - traefik
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`culturedb.hirsch.ee`)"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: culturedb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - traefik

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    networks:
      - traefik
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`culturedb.hirsch.ee`) && PathPrefix(`/api`)"

volumes:
  pgdata: